version: "2"
services:
  poste:
    image: analogic/poste.io
    ports:
      - 25:25
      - 80:80
      - 110:110
      - 143:143
      - 443:443
      - 465:465
      - 587:587
      - 993:993
      - 995:995
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/poste:/data
